
<?php 
 return[
'colour'=>[
'Black' => 'Black', 
'Baby Pink' => 'Baby Pink', 
'Brown' => 'Brown', 
'Blue' => 'Blue', 
'Clear' => 'Clear', 
'Dark Blue' => 'Dark Blue', 
'Golden' => 'Golden', 
'Grey' => 'Grey', 
'Green' => 'Green', 
'Hot Pink' => 'Hot Pink', 
'Lime Green' => 'Lime Green', 
'Mehroon' => 'Mehroon', 
'Orange' => 'Orange', 
'Pink' => 'Pink', 
'Purple' => 'Purple', 
'Red' => 'Red', 
'Sky Blue' => 'Sky Blue', 
'Union Jack Print' => 'Union Jack Print', 
'White' => 'White', 
'Yellow' => 'Yellow', 
'Chocolate' => 'Chocolate', 
'Silver' => 'Silver', 
'Multi Color' => 'Multi Color', 
'Rose Pink' => 'Rose Pink', 
'Peach' => 'Peach', 
'Cream' => 'Cream', 
'Lylac' => 'Lylac', 
'Other' => 'Other', 
'PRINTED' => 'PRINTED', 
'MIX COLOR' => 'MIX COLOR', 
'BEIGE' => 'BEIGE', 
'Clean' => 'Clean', 
] ,
 
'color'=>[
'1' => 'Black', 
'2' => 'Baby Pink', 
'3' => 'Brown', 
'4' => 'Blue', 
'5' => 'Clear', 
'6' => 'Dark Blue', 
'7' => 'Golden', 
'8' => 'Grey', 
'9' => 'Green', 
'10' => 'Hot Pink', 
'11' => 'Lime Green', 
'12' => 'Mehroon', 
'13' => 'Orange', 
'14' => 'Pink', 
'15' => 'Purple', 
'16' => 'Red', 
'17' => 'Sky Blue', 
'18' => 'Union Jack Print', 
'19' => 'White', 
'20' => 'Yellow', 
'21' => 'Chocolate', 
'22' => 'Silver', 
'23' => 'Multi Color', 
'24' => 'Rose Pink', 
'25' => 'Peach', 
'26' => 'Cream', 
'27' => 'Lylac', 
'28' => 'Other', 
'29' => 'PRINTED', 
'30' => 'MIX COLOR', 
'31' => 'BEIGE', 
'32' => 'Clean', 
] 
 ]?>